version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0
  # bridgecrew = checkov
  bridgecrew: bridgecrew/bridgecrew@1.0.5

jobs:
  build-java-application:
    executor: gradle/default
    steps:
      - checkout
      - run: |
          cd demo
          ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test-java-application:
    executor: gradle/default
    steps:
      - checkout
      - run: |
          cd demo
          ./gradlew test
  scan-dockerfile:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          directory: .
# not going to bother pushing since that would require authentication somewhere and it doesn't matter if we're to use this
  # you will need authentication to each and any service.
  build-dockerfile:
    docker:
      - image: cimg/base:2022.09
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: |
          cp /demo/app/build/libs/app.jar ./app.jar
          docker build -t ghcr.io/juliusjuutilainen/app:circleci .

workflows:
  build-and-test:
    jobs:
      - build-java-application
      - scan-dockerfile
      - test-java-application
      - build-dockerfile:
          requires:
            - build-java-application

