version: 2.1

orbs:
  node: circleci/gradle@3.0.0

jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: |
          cd demo
          ./gradlew build