version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build-java-application:
    executor: gradle/default
    steps:
      - checkout
      - run: |
          cd demo
          ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - echo-output

  test-java-application:
      executor: gradle/default
      steps:
        - attach_workspace:
            at: .
        - run: |
            cd demo
            ./gradlew test
            


workflows:
  build-and-test:
    jobs:
      - build-java-application
      - test-java-application