version: 2.1

orbs:
  node: circleci/gradle@3.0.0

jobs:
  build-java-application:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: |
          cd demo
          ./gradlew build

workflows:
  build-and-test:
    jobs:
      - build-java-application