version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build-java-application:
    executor: gradle/default
    steps:
      - checkout
      - run: |
          cd demo
          ./gradlew build

workflows:
  build-and-test:
    jobs:
      - build-java-application