name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: read-all
jobs:
  gradle-build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Build with Gradle Wrapper
      run: |
        cd demo
        ./gradlew build
    - name: Run tests
      run: |
        cd demo
        ./gradlew test
    - name: Test result upload
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./demo/app/build/test-results/test/TEST-org.example.AppTest.xml
    - name: Push build artifact
      uses: actions/upload-artifact@v4
      with:
        name: gradle-artifact
        path: ./demo/app/build/libs/app.jar
        retention-days: 1

  create-and-push-dockerfile:
    permissions: write-all
    needs: gradle-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Retrieve gradle build artifact
        uses: actions/download-artifact@v4
        with:
          name: gradle-artifact
          path: ./app.jar
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkov Scan for Dockerfile
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/juliusjuutilainen/app:latest
          context: .
  display-test-results:
    permissions: read-all
    needs: gradle-build
    runs-on: ubuntu-latest

    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./TEST-org.example.AppTest.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Junit Tests            # Name of the check run which will be created
          path: ./TEST-org.example.AppTest.xml   # Path to test results
          reporter: java-junit
