name: Java CI with Gradle

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
permissions: read-all
jobs:
  gradle-build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Build with Gradle Wrapper
      run: |
        cd demo
        ./gradlew build
    - name: Run tests
      run: |
        cd demo
        ./gradlew test
    - name: Test result upload
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./demo/app/build/test-results/test/TEST-org.example.AppTest.xml
    - name: Push build artifact
      uses: actions/upload-artifact@v4
      with:
        name: gradle-artifact
        path: ./demo/app/build/libs/app.jar
        retention-days: 1

  create-and-push-dockerfile:
    permissions: write-all
    needs: gradle-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Retrieve gradle build artifact
        uses: actions/download-artifact@v4
        with:
          name: gradle-artifact
          path: ./app.jar
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkov Scan for Dockerfile
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app

# there has to be a better way to do the action below, but I'm a newbie at gha so...
      - name: Build and push feature
        if: ${{ steps.extract_branch.outputs.BRANCH != 'main' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/juliusjuutilainen/app:${{ steps.meta.outputs.tags }}
          context: .

      - name: Build and push main
        if: ${{ steps.extract_branch.outputs.BRANCH == 'main' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/juliusjuutilainen/app:latest
          context: .
